"""Soft delete

Revision ID: 465f84e5c2ea
Revises: e2c7d9e721e6
Create Date: 2024-06-27 22:46:14.477349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "465f84e5c2ea"
down_revision: Union[str, None] = "e2c7d9e721e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("photos", "checksum", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("photos", "mime", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("photos", "path", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("trip_records", sa.Column("happened_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("trip_records", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("trips", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "deleted_at")
    op.drop_column("trip_records", "deleted_at")
    op.drop_column("trip_records", "happened_at")
    op.alter_column("photos", "path", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("photos", "mime", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("photos", "checksum", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("photos", "deleted_at")
    # ### end Alembic commands ###
